//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileUploadViewDelete.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class FileUpload
    {
        public int Id { get; set; }
        public int Number { get; set; }

        [DataType(DataType.Date)]
        public System.DateTime DateTime { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public HttpPostedFileBase Image { get; set; }
    }
}
