//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileUploadViewDelete.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int RollNo { get; set; }
        public string Div { get; set; }
        public string Address { get; set; }
        public Nullable<int> age { get; set; }
        public string Gender { get; set; }
        public string EmailID { get; set; }
        public string Password { get; set; }
    }
}
